version: '3.4'

networks:
  dev:
    driver: bridge 

services:
  customer-service:
    image: ${REGISTRY:-service-one}/team-up-api.api:${PLATFORM:-linux}-${TAG:-latest}
    depends_on:
      - "customer_db"
    container_name: team-up-api
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: TeamUpAPI\Dockerfile
    environment:
      - ConnectionString=host=worklog_management_db;port=5435;database=TeamUpDB;username=postgres;password=zaq1@WSX;Pooling=true;
    networks:
      - dev

  customer_db:
    image: postgres:latest
    container_name: TeamUpDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zaq1@WSX
      - POSTGRES_DB=TeamUpDB
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/ 
    networks:
      - dev

volumes:
  customer_data: